### PR TITLE
fix: clear previous error on new input

### PR DESCRIPTION
**Pull request by LordCheta**
This PR addresses this [issue](https://rsklabs.atlassian.net/browse/ROLLUP-407)

### CODE REVIEW

**Comment by annipi** [comment]
Hey should the error message `Can't add own address` disappear when the address is modified? Maybe is out of scope of this PR, the image is changing

**Comment by LordCheta** [comment]
> Hey should the error message `Can't add own address` disappear when the address is modified? Maybe is out of scope of this PR, the image is changing

It's won't present an issue because the validation would never allow you to add a new contact that breaks any validation rules, so the error message disappearing when the inputs are being re-edited just helps with resetting the state of the add new contact process flow

**Comment by annipi** [comment]
> It's won't present an issue because the validation would never allow you to add a new contact that breaks any validation rules, so the error message disappearing when the inputs are being re-edited just helps with resetting the state of the add new contact process flow

What I mean is that once I've modified the address, the error message doesn't disappear even though I'm able to create the contact. But this could be out of scope of this PR avatar fix.
Screenshot 2023-09-15 at 9 36 52 AM

**Review by annipi — APPROVED** [review]
LGTM, error message disappearing when address changed could be for other PR

**Pull request merged**
